[package]
name = "Hydra Co-op"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.9.2" # Add GTK dependency
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
env_logger = "0.9"
log = "0.4"
x11rb = "0.8"
evdev = "0.11"
