[package]
name = "split_screen_launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.14"
gio = "0.14"
glib = "0.14"
clap = "4.0"
log = "0.4"
env_logger = "0.9"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
x11rb = "0.8"
evdev = "0.11"
